spring:
  application:
    name: PersonManagementUsingGraphQL

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    showSql: true
    hibernate:
      ddlAuto: none

  sql:
    init:
      mode: always # Ensure SQL scripts are always executed
      schemaLocations: classpath:schema.sql  # Specify schema initialization script
      dataLocations: classpath:data.sql      # Specify data initialization script
      continueOnError: false
